Repository oneapi-src/oneAPI-samples, pull requests merged in 2023-07, with the labels that each got.

#1770 Remove IoTConnectionTools folder
  Tools/IoTConnectionTools/.gitkeep
  Tools/IoTConnectionTools/aws-pub-sub/CMakeLists.txt
  Tools/IoTConnectionTools/aws-pub-sub/License.txt
  Tools/IoTConnectionTools/aws-pub-sub/README.md
  Tools/IoTConnectionTools/aws-pub-sub/cpp/main.cpp
  Tools/IoTConnectionTools/aws-pub-sub/sample.json
  Tools/IoTConnectionTools/aws-pub-sub/third-party-programs.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/CMakeLists.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/License.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/README.md
  Tools/IoTConnectionTools/azure-iothub-telemetry/certs/certs.c
  Tools/IoTConnectionTools/azure-iothub-telemetry/certs/certs.h
  Tools/IoTConnectionTools/azure-iothub-telemetry/cpp/CMakeLists.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/cpp/iothub_ll_telemetry_sample.c
  Tools/IoTConnectionTools/azure-iothub-telemetry/sample.json
  Tools/IoTConnectionTools/ibm-device/CMakeLists.txt
  Tools/IoTConnectionTools/ibm-device/License.txt
  Tools/IoTConnectionTools/ibm-device/README.md
  Tools/IoTConnectionTools/ibm-device/cpp/deviceSample.c
  Tools/IoTConnectionTools/ibm-device/sample.json
  Tools/IoTConnectionTools/ibm-device/third-party-programs.txt
Labels: 2023.2

#1771 Remove IoTConnectionTools folder
  Tools/IoTConnectionTools/.gitkeep
  Tools/IoTConnectionTools/aws-pub-sub/CMakeLists.txt
  Tools/IoTConnectionTools/aws-pub-sub/License.txt
  Tools/IoTConnectionTools/aws-pub-sub/README.md
  Tools/IoTConnectionTools/aws-pub-sub/cpp/main.cpp
  Tools/IoTConnectionTools/aws-pub-sub/sample.json
  Tools/IoTConnectionTools/aws-pub-sub/third-party-programs.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/CMakeLists.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/License.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/README.md
  Tools/IoTConnectionTools/azure-iothub-telemetry/certs/certs.c
  Tools/IoTConnectionTools/azure-iothub-telemetry/certs/certs.h
  Tools/IoTConnectionTools/azure-iothub-telemetry/cpp/CMakeLists.txt
  Tools/IoTConnectionTools/azure-iothub-telemetry/cpp/iothub_ll_telemetry_sample.c
  Tools/IoTConnectionTools/azure-iothub-telemetry/sample.json
  Tools/IoTConnectionTools/ibm-device/CMakeLists.txt
  Tools/IoTConnectionTools/ibm-device/License.txt
  Tools/IoTConnectionTools/ibm-device/README.md
  Tools/IoTConnectionTools/ibm-device/cpp/deviceSample.c
  Tools/IoTConnectionTools/ibm-device/sample.json
  Tools/IoTConnectionTools/ibm-device/third-party-programs.txt
Labels: 2023.2

#1787 Update ResNet50_Inference_gpu
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference_gpu.ipynb
Labels: 2023.2

#1793 FPGA: modify matrix multiply sample to use variable latency MM hosts
  DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/memory_transfers.hpp
Labels: FPGA, 2023.2

#1799 FPGA: remove unused flag `DEVICE_FLAG`
  DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt
Labels: FPGA, 2024.0

#1803 Updated return type of get_profiling_info
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/src/mem_channel.cpp
Labels: FPGA, 2024.0

#1801 Add C++ option report/matrix multiplication sample
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/License.txt
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/Makefile
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/README.md
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/sample.json
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/driver.c
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/multiply.c
  DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/multiply.h
Labels: 2024.0

#1798 Update Fortran dense linear algebra optimize integral sample
  DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/Makefile
  DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/README.md
  DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/build.bat
  DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/run.bat
  DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/sample.json
Labels: 2024.0

#1797 Update Fortran combinational logic openmp-primes sample
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/Makefile
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/README.md
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/build.bat
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/debug_run.bat
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/run.bat
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/sample.json
  DirectProgramming/Fortran/CombinationalLogic/openmp-primes/src/openmp_sample.f90
Labels: 2024.0
