Repository oneapi-src/oneAPI-samples, pull requests merged in 2023-04, with the labels that each got.

#1519 FPGA: Remove resolved known issues for printf
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/README.md
Labels: FPGA, 2023.2

#1534 GPU required sample.json updates
  DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json
  DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json
  DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/sample.json
  DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
  DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/sample.json
  DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/sample.json
  DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/sample.json
  Libraries/oneMKL/computed_tomography/sample.json
  Libraries/oneMKL/monte_carlo_european_opt/sample.json
  Tools/Benchmarks/STREAM/sample.json
Labels: 2023.2

#1537 Language ID sample update: dataset download and fix typos
  AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/Inference/initialize.sh
  AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/README.md
  AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/Training/initialize.sh
Labels: AI, 2023.1.1

#1426 Update Census sample: Use HDK as backend of Modin
  AI-and-Analytics/End-to-end-Workloads/Census/README.md
  AI-and-Analytics/End-to-end-Workloads/Census/census_modin.ipynb
  AI-and-Analytics/End-to-end-Workloads/Census/sample.json
Labels: AI, 2023.1.1

#1504 improvements for Tf perf analysis
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/README.md
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/analyze
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/analyze_utils.py
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/base_tf_op_duration_pie.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/common_ops_dataframe.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/compare_tf_op_duration_pie.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/compared_tf_op_duration_bar.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/compared_tf_op_duration_ratio_bar.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/mkl_percentage_tf_op_duration_pie.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/report.html
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/tf_ops_1_dataframe.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/tf_ops_2_dataframe.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/tf_ops_shape_2_dataframe.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/unique_base_tf_op_duration_pie.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/Analyze/report_template/unique_compare_tf_op_duration_pie.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/TF_PerfAnalysis.ipynb
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/images/jupyter_kernels.png
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/patch/profile.patch
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/samples/mkl_timeline_resnet50v1_5_fp32_infer_merged_runs.json
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/samples/pretrained_word_embeddings.trace.json.gz
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/samples/stock_timeline_resnet50v1_5_fp32_infer_merged_runs.json
Labels: AI, 2023.1.1

#1510 Multiple Changes to readmes
  AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/Jupyter_Run.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/Jupyter_Save_Py.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
  AI-and-Analytics/Getting-Started-Samples/IntelModin_Vs_Pandas/README.md
  AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/Jupyter_Run.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/Jupyter_Save_Py.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
  AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/Jupyter_Run.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/Jupyter_Save_Py.jpg
  AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
  AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
  AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/Jupyter_Run.jpg
  AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/images/predicted.JPG
  AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/images/sample_digit_images.JPG
  AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md
Labels: AI, 2023.1.1

#1530 FPGA: fix line endings in decompress simulator reference file
  DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/data/snappy/alice29_small_ref.txt
Labels: FPGA, 2023.2

#1529 Remove the FPGA targets from the default make command in the simple-add and vector-add samples
  DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/src/CMakeLists.txt
  DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/src/CMakeLists.txt
Labels: 2023.2

#1521 FPGA: fix CI steps for printf and fpga_compile
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/sample.json
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/sample.json
Labels: FPGA, 2023.2

#1485 Interactive chat based on DialoGPT model using IPEX
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/IntelPytorch_Interactive_Chat_Quantization.ipynb
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/IntelPytorch_Interactive_Chat_Quantization.py
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/License.txt
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/README.md
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/insert.txt
  AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json
Labels: AI, 2023.1.1

#1550 new sample - INC Quantization with PyTorch
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/.ipynb_checkpoints/quantize_with_inc-checkpoint.ipynb
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/.ipynb_checkpoints/requirements-checkpoint.txt
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/License.txt
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/README.MD
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/ci_test.py
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/dataset.py
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/images/inc_speedup.png
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/quantize_with_inc.ipynb
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/requirements.txt
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/sample.json
  AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/third-party-programs.txt
Labels: AI, 2023.1.1

#1558 Update requirements.txt
  AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_AMX_BF16_Training/requirements.txt
Labels: AI, 2023.1.1

#1559 Added gpuRequired to sample.json for 10 samples
  DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json
  DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json
  DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/sample.json
  DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
  DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/sample.json
  DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/sample.json
  DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/sample.json
  Libraries/oneMKL/computed_tomography/sample.json
  Libraries/oneMKL/monte_carlo_european_opt/sample.json
  Tools/Benchmarks/STREAM/sample.json
Labels: 2023.2

#1561 Update sample.json to correct product name
  AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/sample.json
Labels: AI

#1564 FPGA: Only check for device USM support in BSP mode
  DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/main.cpp
  DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/main.cpp
  DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp
  DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/io_streaming/src/FakeIOPipes.hpp
Labels: FPGA, 2023.2

#1552 Fix integer division bug in mem_channel
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/src/mem_channel.cpp
Labels: FPGA, 2023.2

#1565 FPGA: change fpga_compile simulation binary extension
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part1_cpp/src/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2_dpcpp_functor_usm/src/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm/src/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part4_dpcpp_lambda_buffers/src/CMakeLists.txt
Labels: FPGA, 2023.2

#1575 FPGA: Update invocation interfaces sample to reflect that streaming invocation interface and register map arguments is a supported combination
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/invocation_interfaces/README.md
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/invocation_interfaces/assets/streaming_invocation_interface.png
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/invocation_interfaces/src/streaming_functor_model.cpp
Labels: FPGA, 2023.2

#1583 Fix oneAPI-samples issue (#1333)
  DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/README.md
Labels: FPGA

#1584 C++SYCL_FPGA, Features, loop_initiation_interval, update README.md
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_initiation_interval/README.md
Labels: FPGA

#1590 FPGA: Change Code Sample `minimum_latency` to `optimization_targets`
  DirectProgramming/C++SYCL_FPGA/README.md
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/README.md
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/sample.json
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/src/CMakeLists.txt
  DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/src/optimization_targets.cpp
Labels: FPGA, 2023.2
